const DETAILS = [
  {
    id: 101,
    category: '콜드 브루 커피',
    name: '시그니처 더 블랙 콜드 브루',
    engName: 'Signature The Black Cold Brew',
    summary:
      '콜드 브루 전용 원두를 차가운 물로 14시간 동안 추출하여 부드럽고 진한 풍미의 콜드브루를 딜리버리로 원하는 곳에서 편하게 즐겨보세요 (전용 리유저블 보틀 /500ml)',
    desc: '콜드 브루 전용 원두를 차가운 물로 14시간 동안 추출하여 부드럽고 진한 풍미의 콜드브루를 딜리버리로 원하는 곳에서 편하게 즐겨보세요 (전용 리유저블 보틀 /500ml)',
    imgUrl:
      'https://image.istarbucks.co.kr/upload/store/skuimg/2021/08/[9200000003661]_20210819094346334.jpg',
    nutritionFacts: {
      servingSize: 'Bottle(보틀) / 500ml (17 fl oz)',
      kcal: '25',
      fat: '0',
      protein: '0',
      natrium: '50',
      sugars: '0',
      caffeine: '680',
      allergen: false,
    },
  },
  {
    id: 102,
    category: '콜드 브루 커피',
    name: '아이스크림 블렌딩 콜드 브루',
    engName: 'Ice Cream Blending Cold Brew',
    summary:
      '콜드 브루와 바닐라빈이 콕콕 박힌 아이스크림이 블렌딩 되어 진하고 부드러운 콜드 브루 풍미를 느낄 수 있는 콜드 브루\n* 아이스크림 블렌딩 콜드 브루는 BOGO쿠폰, 무료음료 쿠폰 등 일부 쿠폰 사용이 제한됩니다',
    desc: '콜드 브루와 바닐라빈이 콕콕 박힌 아이스크림이 블렌딩 되어 진하고 부드러운 콜드 브루 풍미를 느낄 수 있는 콜드 브루\n* 아이스크림 블렌딩 콜드 브루는 BOGO쿠폰, 무료음료 쿠폰 등 일부 쿠폰 사용이 제한됩니다',
    imgUrl:
      'https://image.istarbucks.co.kr/upload/store/skuimg/2021/06/[9200000003643]_20210623101238875.jpg',
    nutritionFacts: {
      servingSize: 'Tall(톨) / 355ml (12 fl oz)',
      kcal: '420',
      fat: '6',
      protein: '53',
      natrium: '140',
      sugars: '53',
      caffeine: '210',
      allergen: '대두 / 우유',
    },
  },
  {
    id: 103,
    category: '콜드 브루 커피',
    name: '나이트로 바닐라 크림',
    engName: 'Nitro Vanilla Cream',
    summary:
      '부드러운 목넘김의 나이트로 커피와 바닐라 크림의 매력을 한번에 느껴보세요!',
    desc: '부드러운 목넘김의 나이트로 커피와 바닐라 크림의 매력을 한번에 느껴보세요!',
    imgUrl:
      'https://image.istarbucks.co.kr/upload/store/skuimg/2021/04/[9200000002487]_20210426091745609.jpg',
    nutritionFacts: {
      servingSize: 'Tall(톨) / 355ml (12 fl oz)',
      kcal: '75',
      fat: '2',
      protein: '1',
      natrium: '20',
      sugars: '10',
      caffeine: '245',
      allergen: '우유',
    },
  },
  {
    id: 104,
    category: '콜드 브루 커피',
    name: '나이트로 콜드 브루',
    engName: 'Nitro Cold Brew',
    summary:
      '나이트로 커피 정통의 캐스케이딩과 부드러운 콜드 크레마!\n부드러운 목 넘김과 완벽한 밸런스에 커피 본연의 단맛을 경험할 수 있습니다.',
    desc: '차가운 물로 14시간 동안 서서히 완성된 콜드 브루가 질소와 만나\n나이트로 커피 정통의 캐스케이딩과 부드러운 콜드 크레마를 탄생시켰습니다.\n\n부드러운 목넘김과 완벽한 밸런스에 커피 본연의 단맛을 경험할 수 있습니다.\n\n격조 있는 커피가 어울리는 당신께 스타벅스가 지금, 제안합니다.',
    imgUrl:
      'https://image.istarbucks.co.kr/upload/store/skuimg/2021/04/[9200000000479]_20210426091844065.jpg',
    nutritionFacts: {
      servingSize: 'Tall(톨) / 355ml (12 fl oz)',
      kcal: '5',
      fat: '0',
      protein: '0',
      natrium: '5',
      sugars: '0',
      caffeine: '245',
      allergen: false,
    },
  },
  {
    id: 105,
    category: '콜드 브루 커피',
    name: '돌체 콜드 브루',
    engName: 'Dolce Cold Brew',
    summary:
      '무더운 여름철,\n동남아 휴가지에서 즐기는 커피를 떠오르게 하는\n스타벅스 음료의 베스트 x 베스트 조합인\n돌체 콜드 브루를 만나보세요!',
    desc: '무더운 여름철, 동남아 휴가지에서 즐기는 커피를 떠오르게 하는 스타벅스 음료의 베스트 x 베스트 조합인 돌체 콜드 브루를 만나보세요!',
    imgUrl:
      'https://image.istarbucks.co.kr/upload/store/skuimg/2021/04/[9200000002081]_20210415133657016.jpg',
    nutritionFacts: {
      servingSize: 'Tall(톨) / 355ml (12 fl oz)',
      kcal: '265',
      fat: '9',
      protein: '8',
      natrium: '115',
      sugars: '29',
      caffeine: '150',
      allergen: '우유',
    },
  },
  {
    id: 106,
    category: '콜드 브루 커피',
    name: '바닐라 크림 콜드 브루',
    engName: 'Vanilla Cream Cold Brew',
    summary:
      '콜드 브루에 더해진 바닐라 크림으로 깔끔하면서 달콤한 콜드 브루를 새롭게 즐길 수 있는 음료입니다.',
    desc: '콜드 브루에 더해진 바닐라 크림으로 깔끔하면서 달콤한 콜드 브루를 새롭게 즐길 수 있는 음료입니다.',
    imgUrl:
      'https://image.istarbucks.co.kr/upload/store/skuimg/2021/04/[9200000000487]_20210430112319174.jpg',
    nutritionFacts: {
      servingSize: 'Tall(톨) / 355ml (12 fl oz)',
      kcal: '125',
      fat: '6',
      protein: '3',
      natrium: '58',
      sugars: '11',
      caffeine: '150',
      allergen: '우유',
    },
  },
  {
    id: 107,
    category: '콜드 브루 커피',
    name: '벨벳 다크 모카 나이트로',
    engName: 'Velvet Dark Mocha Nitro',
    summary:
      '다크 초콜릿 모카의 진한 바디감과 함께\n헤이즐넛 향과 달콤한 카라멜 크림 폼으로\n벨벳같은 부드러움까지 살린 리저브 나이트로 커피',
    desc: '다크 초콜릿 모카의 진한 바디감과 함께\n헤이즐넛 향과 달콤한 카라멜 크림 폼으로\n벨벳같은 부드러움까지 살린 리저브 나이트로 커피',
    imgUrl:
      'https://image.istarbucks.co.kr/upload/store/skuimg/2021/03/[9200000003509]_20210322093452556.jpg',
    nutritionFacts: {
      servingSize: 'Tall(톨) / 355ml (12 fl oz)',
      kcal: '150',
      fat: '6',
      protein: '2',
      natrium: '15',
      sugars: '17',
      caffeine: '160',
      allergen: false,
    },
  },
  {
    id: 108,
    category: '콜드 브루 커피',
    name: '제주 비자림 콜드 브루',
    engName: 'Jeju Forest Cold Brew',
    summary:
      '[제주지역 한정음료] 제주 천년의 숲 비자림을 연상시키는\n음료로 제주에서 유기농 말차로 만든\n파우더와 Cold Brew를 활용한 음료.',
    desc: '[제주지역 한정음료] 제주 천년의 숲 비자림을 연상시키는 음료로 제주에서 유기농 말차로 만든 파우더와 Cold Brew를 활용한 음료.',
    imgUrl:
      'https://image.istarbucks.co.kr/upload/store/skuimg/2020/09/[9200000002672]_20200921171223958.jpg',
    nutritionFacts: {
      servingSize: 'Grande(그란데) / 473ml (16 fl oz)',
      kcal: '340',
      fat: '8',
      protein: '10',
      natrium: '115',
      sugars: '44',
      caffeine: '105',
      allergen: false,
    },
  },
  {
    id: 109,
    category: '콜드 브루 커피',
    name: '콜드 브루',
    engName: 'Cold Brew',
    summary:
      '스타벅스 바리스타의 정성으로 탄생한 콜드 브루!콜드 브루 전용 원두를 차가운 물로 14시간 동안 추출하여 한정된 양만 제공됩니다.깊은 풍미의 새로운 커피 경험을 즐겨보세요.',
    desc: '스타벅스 바리스타의 정성으로 탄생한 콜드 브루!\n콜드 브루 전용 원두를 차가운 물로 14시간 동안 추출하여 한정된 양만 제공됩니다.\n깊은 풍미의 새로운 커피 경험을 즐겨보세요.',
    imgUrl:
      'https://image.istarbucks.co.kr/upload/store/skuimg/2021/04/[9200000000038]_20210430113202595.jpg',
    nutritionFacts: {
      servingSize: 'Tall(톨) / 355ml (12 fl oz)',
      kcal: '5',
      fat: '0',
      protein: '0',
      natrium: '11',
      sugars: '0',
      caffeine: '150',
      allergen: false,
    },
  },
  {
    id: 110,
    category: '콜드 브루 커피',
    name: '콜드 브루 몰트',
    engName: 'Cold Brew Malt',
    summary:
      '[리저브 전용음료] 리저브 콜드 브루, 바닐라 아이스크림, 몰트가 블렌딩된 리저브만의 쉐이크',
    desc: '[리저브 전용음료] 리저브 콜드 브루, 바닐라 아이스크림, 몰트가 블렌딩된 리저브만의 쉐이크',
    imgUrl:
      'https://image.istarbucks.co.kr/upload/store/skuimg/2021/02/[9200000001636]_20210225093600541.jpg',
    nutritionFacts: {
      servingSize: 'Tall(톨) / 355ml (12 fl oz)',
      kcal: '510',
      fat: '20',
      protein: '10',
      natrium: '147.8',
      sugars: '40',
      caffeine: '150',
      allergen: '대두 / 우유',
    },
  },
  {
    id: 111,
    category: '콜드 브루 커피',
    name: '콜드 브루 오트 라떼',
    engName: 'Cold Brew Oat Latte',
    summary:
      '콜드 브루의 풍미와 깔끔한 오트 밀크가 어우러진 달콤 고소한 라떼.식물성 밀크를 사용해 모든 고객이 부담없이 즐길 수 있는 콜드 브루 음료',
    desc: '콜드 브루의 풍미와 깔끔한 오트 밀크가 어우러진 달콤 고소한 라떼.\n식물성 밀크를 사용해 모든 고객이 부담없이 즐길 수 있는 콜드 브루 음료',
    imgUrl:
      'https://image.istarbucks.co.kr/upload/store/skuimg/2021/04/[9200000003285]_20210416154437226.jpg',
    nutritionFacts: {
      servingSize: 'Grande(그란데) / 473ml (16 fl oz)',
      kcal: '105',
      fat: '0.3',
      protein: '1',
      natrium: '95',
      sugars: '11',
      caffeine: '65',
      allergen: false,
    },
  },
  {
    id: 112,
    category: '콜드 브루 커피',
    name: '콜드 브루 플로트',
    engName: 'Cold Brew Float',
    summary:
      '[리저브 전용음료] 리저브 콜드 브루 위에 녹아 내리는 한 스쿱의 바닐라 아이스크림',
    desc: '[리저브 전용음료] 리저브 콜드 브루 위에 녹아 내리는 한 스쿱의 바닐라 아이스크림',
    imgUrl:
      'https://image.istarbucks.co.kr/upload/store/skuimg/2021/02/[9200000001635]_20210225092236754.jpg',
    nutritionFacts: {
      servingSize: 'Tall(톨) / 355ml (12 fl oz)',
      kcal: '230',
      fat: '10',
      protein: '3',
      natrium: '69',
      sugars: '18',
      caffeine: '150',
      allergen: '우유',
    },
  },
  {
    id: 113,
    category: '콜드 브루 커피',
    name: '프렌치 애플 타르트 나이트로',
    engName: 'French Apple Tarte Nitro',
    summary:
      '카라멜향을 머금은 애플의 달콤함과\n부드러운 콜드 크레마를 조화롭게\n느낄 수 있는 리저브 나이트로 음료',
    desc: '카라멜향을 머금은 애플의 달콤함과\n부드러운 콜드 크레마를 조화롭게\n느낄 수 있는 리저브 나이트로 음료',
    imgUrl:
      'https://image.istarbucks.co.kr/upload/store/skuimg/2021/03/[9200000003507]_20210322093414448.jpg',
    nutritionFacts: {
      servingSize: 'Tall(톨) / 355ml (12 fl oz)',
      kcal: '80',
      fat: '0',
      protein: '0',
      natrium: '0',
      sugars: '19',
      caffeine: '145',
      allergen: false,
    },
  },
  {
    id: 201,
    category: '브루드 커피',
    name: '아이스 커피',
    engName: 'Iced Coffee',
    summary: '깔끔하고 상큼함이 특징인 시원한 아이스 커피',
    desc: '케냐, 하우스 블렌드 등 약간의 산미가 있는 커피를 드립 방식으로 추출한 후 얼음과 함께 제공하는 커피 입니다. 아이스 커피로 적합한 프리미엄 원두를 이용하여 깔끔하고 상큼한 맛을 느끼실 수 있습니다.',
    imgUrl:
      'https://image.istarbucks.co.kr/upload/store/skuimg/2021/04/[106509]_20210430111852999.jpg',
    nutritionFacts: {
      servingSize: 'Tall(톨) / 355ml (12 fl oz)',
      kcal: '5',
      fat: '0',
      protein: '0',
      natrium: '10',
      sugars: '0',
      caffeine: '140',
      allergen: false,
    },
  },
  {
    id: 202,
    category: '브루드 커피',
    name: '오늘의 커피',
    engName: 'Brewed Coffee',
    summary: '신선하게 브루드(Brewed)되어 원두의 다양함이 살아있는 커피',
    desc: '시즌에 어울리는 하나의 원두 종류를 선정하여 신선하게 브루드(Brewed)되어 제공되는 드립커피로 원두 커피의 풍부한 맛과 향을 따뜻하게 즐기실 수 있습니다.',
    imgUrl:
      'https://image.istarbucks.co.kr/upload/store/skuimg/2021/04/[2]_20210430111934246.jpg',
    nutritionFacts: {
      servingSize: 'Tall(톨) / 355ml (12 fl oz)',
      kcal: '5',
      fat: '0',
      protein: '0',
      natrium: '10',
      sugars: '0',
      caffeine: '260',
      allergen: false,
    },
  },
];

export default DETAILS;
